sudo: required

services:
  - docker

script:
  - docker build -t sphinx .
  - docker run -d -p 5000:5000 -e PORT=5000 sphinx:latest
  - read -t3 -p "wating for waitress...\n"; docker ps -a
  - curl --fail localhost:5000
